version: 2

updates:
  # Update npm packages
  - package-ecosystem: npm
    directory: /
    open-pull-requests-limit: 10

    # Group packages into shared PR
    groups:
      babel:
        patterns:
          - '@babel/*'

      lint:
        patterns:
          - '@typescript-eslint/*'
          - 'editorconfig-checker'
          - 'eslint'
          - 'eslint-*'
          - 'standard'
          - 'prettier'
          - 'stylelint'
          - 'stylelint-*'
          - 'typescript'

      percy:
        patterns:
          - '@percy/*'

      postcss:
        patterns:
          - 'autoprefixer'
          - 'cssnano'
          - 'cssnano-*'
          - 'postcss'
          - 'postcss-*'

      rollup:
        patterns:
          - '@rollup/*'
          - 'rollup'
          - 'rollup-*'

      test:
        patterns:
          - '@axe-core/*'
          - '@jest/*'
          - '@puppeteer/*'
          - '@types/jest'
          - '@types/jest-*'
          - 'jest'
          - 'jest-*'
          - 'puppeteer'
          - 'puppeteer-*'

    reviewers:
      - alphagov/design-system-developers

    # Schedule run every Monday, local time
    schedule:
      interval: weekly
      time: '10:30'
      timezone: 'Europe/London'

    versioning-strategy: increase

    allow:
      - dependency-type: direct

  # Update GitHub Actions
  - package-ecosystem: github-actions
    directory: /
    reviewers:
      - alphagov/design-system-developers

    # Schedule run every Monday, local time
    schedule:
      interval: weekly
      time: '10:30'
      timezone: 'Europe/London'
