version: 2

updates:
  # Update npm packages
  - package-ecosystem: npm
    directory: /
    open-pull-requests-limit: 10
    reviewers:
      - alphagov/design-system-developers

    # Schedule run every Monday, local time
    schedule:
      interval: weekly
      time: '10:30'
      timezone: 'Europe/London'

    versioning-strategy: increase

    allow:
      - dependency-type: direct

  # Update GitHub Actions
  - package-ecosystem: github-actions
    directory: /
    reviewers:
      - alphagov/design-system-developers

    # Schedule run every Monday, local time
    schedule:
      interval: weekly
      time: '10:30'
      timezone: 'Europe/London'
