name: Install dependencies

runs:
  using: composite

  steps:
    - name: Cache dependencies
      uses: actions/cache@v3
      id: npm-install-cache

      with:
        # Restore `node_modules` cache (unless lockfile changes)
        key: npm-install-cache-${{ hashFiles('package-lock.json') }}
        path: |
          .cache/puppeteer
          node_modules

    - name: Setup Node.js
      uses: ./.github/workflows/actions/setup-node
      id: setup-node

      with:
        # Restore global `~/.npm` cache (unless lockfile changes)
        use-cache: ${{ steps.npm-install-cache.outputs.cache-hit != 'true' }}

    - name: Install dependencies
      id: install-node

      # Skip install when dependencies are cached
      if: steps.npm-install-cache.outputs.cache-hit != 'true'
      shell: bash
      run: npm ci
