name: Install dependencies

runs:
  using: composite

  steps:
    - name: Log GitHub context
      shell: bash
      run: echo "github.sha ${{github.sha}} - github.event.pull_request.head.sha ${{github.event.pull_request.head.sha}}"

    - name: Cache dependencies
      uses: actions/cache@v3.3.1
      id: npm-install-cache

      with:
        # Use faster GNU tar for all runners
        enableCrossOsArchive: true

        # Restore `node_modules` cache (unless packages change)
        key: npm-install-${{ runner.os }}-${{ hashFiles('package-lock.json', '**/package.json') }}
        path: |
          node_modules
          .github/workflows/scripts/node_modules
          docs/examples/*/node_modules
          packages/*/node_modules
          shared/*/node_modules

    - name: Setup Node.js
      uses: ./.github/workflows/actions/setup-node
      id: setup-node

      with:
        # Restore global `~/.npm` cache (unless packages change)
        use-cache: ${{ steps.npm-install-cache.outputs.cache-hit != 'true' }}

    - name: Install dependencies
      id: install-node

      # Skip install when dependencies are cached
      if: steps.npm-install-cache.outputs.cache-hit != 'true'
      shell: bash
      run: npm ci
