name: Performance

on:
  pull_request:
    branches:
      - main

jobs:
  install:
    name: Install
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        uses: ./.github/workflows/actions/install-node

  size:
    name: Size Limit
    runs-on: ubuntu-latest
    needs: [install]

    strategy:
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Restore dependencies
        uses: ./.github/workflows/actions/install-node

      - name: Run size-limit
        run: npm run size
