name: Tests

on:
  pull_request:

  push:
    branches:
      - main
      - 'feature/**'
      - 'support/**'

  workflow_dispatch:

concurrency:
   group: tests-${{ github.head_ref || github.run_id }}
   cancel-in-progress: true

env:
  INSTALL_CACHE_DIR: |
    .cache/puppeteer
    node_modules

  TASK_CACHE_DIR: |
    .cache/eslint
    .cache/jest
    .cache/stylelint

jobs:
  run-tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache dependencies
        uses: actions/cache@v3
        id: npm-cache
        with:
          key: npm-cache-${{ hashFiles('package-lock.json') }}
          path: ${{ env.INSTALL_CACHE_DIR }}

      - name: Cache tasks
        uses: actions/cache@v3
        with:
          key: task-cache
          path: ${{ env.TASK_CACHE_DIR }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          cache: ${{ steps.npm-cache.outputs.cache-hit != 'true' && 'npm' || '' }}
          node-version-file: .nvmrc

      - name: Install dependencies
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Build
        run: |
          npm run build:compile
          npm run build:package
          npm run build:dist

      - name: Run test projects
        run: |
          npx jest --color --selectProjects "Nunjucks macro tests"
          npx jest --color --selectProjects "JavaScript unit tests" --coverage --testLocationInResults
          npx jest --color --selectProjects "JavaScript behaviour tests"

      - name: Send screenshots to Percy
        run: npx percy exec -- jest --color --selectProjects "JavaScript component tests"
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}

      - name: Save test coverage
        uses: actions/upload-artifact@v3
        with:
          name: Test coverage
          path: coverage
          if-no-files-found: ignore
