name: Tests

on:
  pull_request:

  push:
    branches:
      - main
      - 'feature/**'
      - 'support/**'

  workflow_dispatch:

concurrency:
   group: tests-${{ github.head_ref || github.run_id }}
   cancel-in-progress: true

env:
  TASK_CACHE_DIR: |
    .cache/eslint
    .cache/jest
    .cache/stylelint

jobs:
  run-tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build
        uses: ./.github/workflows/actions/build

      - name: Cache tasks
        uses: actions/cache@v3
        with:
          key: task-cache
          path: ${{ env.TASK_CACHE_DIR }}

      - name: Lint
        run: npm run lint

      - name: Run test projects
        run: |
          npx jest --color --selectProjects "Nunjucks macro tests"
          npx jest --color --selectProjects "JavaScript unit tests" --coverage --testLocationInResults
          npx jest --color --selectProjects "JavaScript behaviour tests"

      - name: Send screenshots to Percy
        run: npx percy exec -- jest --color --selectProjects "JavaScript component tests"
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}

      - name: Save test coverage
        uses: actions/upload-artifact@v3
        with:
          name: Test coverage
          path: coverage
          if-no-files-found: ignore
